export const SAMPLE_REPORT = {
  address: "0x742d35Cc6634C0532925a3b8D4C9E2b3A8c5f1e2",
  ensName: "cryptodegen.eth",
  generatedAt: "2026-05-31T14:22:00Z",

  overview: {
    totalBalanceUsd: 847_320.44,
    totalBalanceChange24h: +12.4,
    walletAgeDays: 1284,
    firstSeen: "2022-11-14",
    lastActive: "2026-05-31",
    totalTransactions: 4_817,
    chains: ["ethereum", "base", "solana", "arbitrum", "polygon"],
    nftCount: 143,
    defiPositions: 7,
    riskScore: 62,
  },

  connectedWallets: [
    {
      address: "0x9A3f...c4B2",
      full: "0x9A3f8d1e2b5c4f6a7d8e9f0a1b2c3d4e5f6a7c4B2",
      label: "Primary Funding Wallet",
      relation: "Likely same owner",
      confidence: 91,
      balanceUsd: 210_000,
      chain: "ethereum",
      note: "Funded this wallet in 3 transactions. Same gas token source.",
    },
    {
      address: "0x1Fe2...9d8C",
      full: "0x1Fe2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9d8C",
      label: "NFT Trading Wallet",
      relation: "Linked via NFT transfer",
      confidence: 78,
      balanceUsd: 34_400,
      chain: "ethereum",
      note: "Received 12 NFTs from this wallet. Likely same operator managing separate strategies.",
    },
    {
      address: "8xKm...4rPq",
      full: "8xKmN2bP3cQ4dR5eS6fT7gU8hV9iW0jX1kY2lZ3m4rPq",
      label: "Solana Companion",
      relation: "Cross-chain bridge pattern",
      confidence: 65,
      balanceUsd: 18_200,
      chain: "solana",
      note: "Bridge deposits match timing within 3 minutes of ETH withdrawals.",
    },
  ],

  cexFlows: [
    {
      exchange: "Coinbase",
      type: "onboarding",
      direction: "inbound",
      estimatedVolume: 320_000,
      txCount: 8,
      firstDate: "2022-11-14",
      lastDate: "2023-08-22",
      confidence: 88,
      note: "Initial capital source. Large round-number deposits ($25K, $50K, $100K) consistent with CEX withdrawal patterns.",
    },
    {
      exchange: "Binance",
      type: "offboarding",
      direction: "outbound",
      estimatedVolume: 95_000,
      txCount: 14,
      firstDate: "2023-03-10",
      lastDate: "2024-12-01",
      confidence: 73,
      note: "Recurring small withdrawals to known Binance hot wallet cluster.",
    },
    {
      exchange: "Kraken",
      type: "onboarding",
      direction: "inbound",
      estimatedVolume: 48_000,
      txCount: 3,
      firstDate: "2024-01-15",
      lastDate: "2024-07-20",
      confidence: 67,
      note: "Sporadic top-ups likely from stablecoin liquidation on Kraken.",
    },
  ],

  classification: {
    primary: "DeFi Power User",
    secondary: "Memecoin Degen",
    confidence: 84,
    reasoning:
      "Wallet shows sophisticated DeFi interaction patterns (Uniswap V3, Aave, Curve) accounting for ~60% of gas spend, combined with a distinct high-frequency memecoin rotation strategy visible in Q1 2025 through Q2 2026. The subject does not appear to be a long-term HODLer — average holding period is 23 days across all non-stablecoin assets.",
    traits: [
      { label: "Risk Appetite", value: "High", score: 78 },
      { label: "DeFi Sophistication", value: "Advanced", score: 85 },
      { label: "Trading Frequency", value: "Active (avg 3.7 tx/day)", score: 72 },
      { label: "Diversification", value: "Moderate", score: 55 },
      { label: "Long-Term Conviction", value: "Low", score: 22 },
    ],
  },

  buyingBehavior: [
    {
      category: "Established Memecoins",
      allocation: 28,
      examples: ["PEPE", "WIF", "BONK", "SHIB"],
      avgHoldDays: 11,
      profitability: "positive",
      note: "Buys on trending volume spikes, sells within 2 weeks. Pattern suggests monitoring CT/Telegram sentiment.",
    },
    {
      category: "Base AI Ecosystem",
      allocation: 22,
      examples: ["VIRTUAL", "AIXBT", "COOKIE", "GRIFFAIN"],
      avgHoldDays: 34,
      profitability: "positive",
      note: "Early-mover pattern in Base AI tokens. Likely in private Alpha groups — consistently buys 12–48 hrs before volume peaks.",
    },
    {
      category: "Low-Cap Trenching",
      allocation: 18,
      examples: ["Unknown tokens <$5M mcap"],
      avgHoldDays: 7,
      profitability: "mixed",
      note: "Buys in 3–5 tranches. Very high variance — 40% of these positions go to near-zero, 15% are 5–20x winners.",
    },
    {
      category: "Blue Chip DeFi",
      allocation: 17,
      examples: ["UNI", "AAVE", "CRV", "LDO"],
      avgHoldDays: 180,
      profitability: "neutral",
      note: "Held for governance and yield farming. Not actively traded.",
    },
    {
      category: "ETH / wETH",
      allocation: 15,
      examples: ["ETH", "wETH", "stETH"],
      avgHoldDays: 400,
      profitability: "positive",
      note: "Core long-term position. ETH staked via Lido, generating passive yield.",
    },
  ],

  pnl: {
    allTimeUsd: +284_500,
    allTimePercent: +89.2,
    realizedUsd: +196_200,
    unrealizedUsd: +88_300,
    totalFeesPaidUsd: 12_840,
    breakdown: [
      { category: "Memecoins", pnl: +142_300, txCount: 287, winRate: 52 },
      { category: "Base AI Tokens", pnl: +98_700, txCount: 64, winRate: 71 },
      { category: "Low-Cap Trenching", pnl: -18_400, txCount: 412, winRate: 34 },
      { category: "Blue Chip DeFi", pnl: +31_200, txCount: 38, winRate: 79 },
      { category: "NFTs", pnl: +30_700, txCount: 143, winRate: 58 },
    ],
    peakPortfolioUsd: 1_240_000,
    peakDate: "2025-11-14",
    tradeFrequency: "3.7 trades/day avg",
    bestMonth: { month: "Nov 2025", pnl: +187_400 },
    worstMonth: { month: "Apr 2024", pnl: -41_200 },
  },

  holdings: [
    { symbol: "ETH", name: "Ethereum", chain: "ethereum", balanceUsd: 284_100, amount: "91.4 ETH", change24h: +2.1, allocation: 33.5 },
    { symbol: "USDC", name: "USD Coin", chain: "ethereum", balanceUsd: 150_000, amount: "150,000 USDC", change24h: 0, allocation: 17.7 },
    { symbol: "VIRTUAL", name: "Virtuals Protocol", chain: "base", balanceUsd: 98_400, amount: "42,180 VIRTUAL", change24h: +8.4, allocation: 11.6 },
    { symbol: "stETH", name: "Lido Staked ETH", chain: "ethereum", balanceUsd: 87_200, amount: "28.0 stETH", change24h: +2.0, allocation: 10.3 },
    { symbol: "WIF", name: "dogwifhat", chain: "solana", balanceUsd: 62_400, amount: "21,500 WIF", change24h: -3.2, allocation: 7.4 },
    { symbol: "PEPE", name: "Pepe", chain: "ethereum", balanceUsd: 44_800, amount: "12.1B PEPE", change24h: +5.7, allocation: 5.3 },
    { symbol: "AAVE", name: "Aave", chain: "ethereum", balanceUsd: 38_900, amount: "94 AAVE", change24h: +1.2, allocation: 4.6 },
    { symbol: "ARB", name: "Arbitrum", chain: "arbitrum", balanceUsd: 29_100, amount: "38,400 ARB", change24h: -1.8, allocation: 3.4 },
    { symbol: "BONK", name: "Bonk", chain: "solana", balanceUsd: 18_220, amount: "8.4B BONK", change24h: +12.1, allocation: 2.2 },
    { symbol: "Various", name: "Other tokens", chain: "multiple", balanceUsd: 34_200, amount: "14 tokens", change24h: 0, allocation: 4.0 },
  ],

  defiPositions: [
    {
      protocol: "Aave V3",
      chain: "ethereum",
      type: "Lending",
      valueUsd: 124_000,
      details: "Deposited 40 ETH as collateral, borrowed 48,000 USDC at 68% LTV",
      apy: 3.2,
      healthFactor: 1.72,
    },
    {
      protocol: "Uniswap V3",
      chain: "ethereum",
      type: "LP Position",
      valueUsd: 58_400,
      details: "ETH/USDC 0.05% pool, range 2,800–3,600",
      apy: 14.8,
      healthFactor: null,
    },
    {
      protocol: "Lido",
      chain: "ethereum",
      type: "Staking",
      valueUsd: 87_200,
      details: "28 stETH earning ~3.8% APY",
      apy: 3.8,
      healthFactor: null,
    },
    {
      protocol: "Curve Finance",
      chain: "ethereum",
      type: "LP Position",
      valueUsd: 22_100,
      details: "3pool (USDC/DAI/USDT)",
      apy: 6.4,
      healthFactor: null,
    },
  ],

  inferences: [
    {
      label: "Insider Information Access",
      confidence: 72,
      color: "amber",
      description:
        "Subject consistently enters Base AI token positions 12–48 hours before major volume events in 9 of 12 tracked cases. This pattern is statistically improbable (~0.3% chance at random) and suggests access to private alpha channels, early Discord/Telegram leaks, or network connections to project insiders.",
    },
    {
      label: "Professional or Semi-Professional Trader",
      confidence: 81,
      color: "cyan",
      description:
        "Trading activity shows deliberate position sizing (rarely >15% of portfolio in single asset), consistent stop-loss behavior in low-cap positions, and MEV-resistant transaction patterns (use of Flashbots RPC). Subject likely treats this as primary or significant secondary income.",
    },
    {
      label: "Based in UTC+0 to UTC+8 Timezone",
      confidence: 58,
      color: "purple",
      description:
        "Peak transaction activity clusters between 02:00–10:00 UTC, suggesting the subject is awake during Asian or European morning hours. This narrows geographic location to Europe, East Africa, South Asia, or East Asia.",
    },
    {
      label: "Multiple People or Automated Bots",
      confidence: 44,
      color: "amber",
      description:
        "Simultaneous multi-chain activity observed on 14 occasions (transactions on Ethereum and Solana within the same 30-second window) suggest either automation scripts/bots or multiple individuals sharing access to this wallet cluster.",
    },
    {
      label: "Tax Optimization Strategy",
      confidence: 63,
      color: "green",
      description:
        "Realized losses consistently cluster in late November–December each year (2023, 2024, 2025), consistent with tax-loss harvesting strategies common in jurisdictions with annual capital gains accounting periods (US, UK, Germany).",
    },
  ],

  timeline: [
    { date: "2022-11-14", event: "Wallet Created", type: "setup", value: null, chain: "ethereum" },
    { date: "2022-11-15", event: "Funded $50,000 from Coinbase", type: "funding", value: 50000, chain: "ethereum" },
    { date: "2022-12-08", event: "First DeFi interaction (Uniswap)", type: "defi", value: null, chain: "ethereum" },
    { date: "2023-01-22", event: "Purchased 120 ETH at ~$1,580", type: "buy", value: 189600, chain: "ethereum" },
    { date: "2023-06-14", event: "First memecoin trade (PEPE)", type: "memecoin", value: 8400, chain: "ethereum" },
    { date: "2023-11-02", event: "Funded $100,000 from Coinbase", type: "funding", value: 100000, chain: "ethereum" },
    { date: "2024-03-18", event: "Portfolio peaked at $480K", type: "milestone", value: 480000, chain: "multiple" },
    { date: "2024-04-12", event: "Major loss event (low-caps)", type: "loss", value: -41200, chain: "ethereum" },
    { date: "2024-09-05", event: "Bridged to Base, began AI token accumulation", type: "strategy", value: null, chain: "base" },
    { date: "2025-01-18", event: "VIRTUAL position: +$84,000 gain", type: "win", value: 84000, chain: "base" },
    { date: "2025-11-14", event: "Portfolio peaked at $1.24M (all-time high)", type: "milestone", value: 1240000, chain: "multiple" },
    { date: "2026-05-31", event: "Current balance: $847,320", type: "current", value: 847320, chain: "multiple" },
  ],
};

export type SampleReport = typeof SAMPLE_REPORT;
